default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
<<<<<<< HEAD
  user: lucas
  password: 12345
=======
  username: postgres
  password: 'senha'
>>>>>>> c0191442559e5809b680117698943a4e04fb9816

development:
  <<: *default
  database: bwc_api

test:
  <<: *default
  database: bwc_api_test

production:
  <<: *default
  database: bwc_api_production
  username: bwc_api
  password: <%= ENV["BWC_API_DATABASE_PASSWORD"] %>
