default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  user: lucas
  password: 12345

development:
  <<: *default
  database: bwc_api

test:
  <<: *default
  database: bwc_api_test

production:
  <<: *default
  database: bwc_api_production
  username: bwc_api
  password: <%= ENV["BWC_API_DATABASE_PASSWORD"] %>
